language: scala
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache/coursier
    - $HOME/.coursier
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.coursier -name "*.lock" -delete
  - find $HOME/.cache/coursier -name "*.lock" -delete
scala:
  - 2.12.12
jdk:
  - oraclejdk8
  - openjdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION validate
