name: CI
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os   : [ubuntu-latest]
        scala: [2.12.20]
        java : [8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: coursier/setup-action@v1.3.8
        with:
          jvm: "adopt:${{ matrix.java }}"

      - name: Cache
        uses: coursier/cache-action@v6.4.6

      - name: Test
        run: sbt ++${{ matrix.scala }} validate
