on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

name: Scala Steward

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1.1.4
      - name: Scala Steward GitHub Action
        uses: scala-steward-org/scala-steward-action@v2.71.0
            
